/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StrategyIntensiveRouteImport } from './routes/strategy-intensive'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NextStepsRouteImport } from './routes/next-steps'
import { Route as NextKeynoteRouteImport } from './routes/next-keynote'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as KeynoteRouteImport } from './routes/keynote'
import { Route as IntensiveRouteImport } from './routes/intensive'
import { Route as ConfirmedRouteImport } from './routes/confirmed'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as OfferVipUpgradeRouteImport } from './routes/offer/vip-upgrade'
import { Route as OfferStrategyIntensiveRouteImport } from './routes/offer/strategy-intensive'
import { Route as OfferMentorshipRouteImport } from './routes/offer/mentorship'
import { Route as OfferKeynoteRouteImport } from './routes/offer/keynote'
import { Route as OfferImplementationVaultRouteImport } from './routes/offer/implementation-vault'
import { Route as CalendarDay2DoticsRouteImport } from './routes/calendar.day2[.]ics'
import { Route as CalendarDay1DoticsRouteImport } from './routes/calendar.day1[.]ics'
import { Route as ApplyMentorshipRouteImport } from './routes/apply.mentorship'
import { Route as ApiPublicMentorshipApplicationRouteImport } from './routes/api/public/mentorship-application'
import { Route as ApiPublicKeynoteWaitlistRouteImport } from './routes/api/public/keynote-waitlist'
import { Route as ApiPublicWebhooksCommasRouteImport } from './routes/api/public/webhooks/commas'
import { Route as ApiPublicResourcesReadRouteImport } from './routes/api/public/resources/read'
import { Route as ApiPublicResourcesExchangeRouteImport } from './routes/api/public/resources/exchange'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyIntensiveRoute = StrategyIntensiveRouteImport.update({
  id: '/strategy-intensive',
  path: '/strategy-intensive',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NextStepsRoute = NextStepsRouteImport.update({
  id: '/next-steps',
  path: '/next-steps',
  getParentRoute: () => rootRouteImport,
} as any)
const NextKeynoteRoute = NextKeynoteRouteImport.update({
  id: '/next-keynote',
  path: '/next-keynote',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const KeynoteRoute = KeynoteRouteImport.update({
  id: '/keynote',
  path: '/keynote',
  getParentRoute: () => rootRouteImport,
} as any)
const IntensiveRoute = IntensiveRouteImport.update({
  id: '/intensive',
  path: '/intensive',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmedRoute = ConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const OfferVipUpgradeRoute = OfferVipUpgradeRouteImport.update({
  id: '/offer/vip-upgrade',
  path: '/offer/vip-upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferStrategyIntensiveRoute = OfferStrategyIntensiveRouteImport.update({
  id: '/offer/strategy-intensive',
  path: '/offer/strategy-intensive',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferMentorshipRoute = OfferMentorshipRouteImport.update({
  id: '/offer/mentorship',
  path: '/offer/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferKeynoteRoute = OfferKeynoteRouteImport.update({
  id: '/offer/keynote',
  path: '/offer/keynote',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferImplementationVaultRoute =
  OfferImplementationVaultRouteImport.update({
    id: '/offer/implementation-vault',
    path: '/offer/implementation-vault',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalendarDay2DoticsRoute = CalendarDay2DoticsRouteImport.update({
  id: '/calendar/day2.ics',
  path: '/calendar/day2.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarDay1DoticsRoute = CalendarDay1DoticsRouteImport.update({
  id: '/calendar/day1.ics',
  path: '/calendar/day1.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyMentorshipRoute = ApplyMentorshipRouteImport.update({
  id: '/apply/mentorship',
  path: '/apply/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMentorshipApplicationRoute =
  ApiPublicMentorshipApplicationRouteImport.update({
    id: '/api/public/mentorship-application',
    path: '/api/public/mentorship-application',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKeynoteWaitlistRoute =
  ApiPublicKeynoteWaitlistRouteImport.update({
    id: '/api/public/keynote-waitlist',
    path: '/api/public/keynote-waitlist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksCommasRoute = ApiPublicWebhooksCommasRouteImport.update({
  id: '/api/public/webhooks/commas',
  path: '/api/public/webhooks/commas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResourcesReadRoute = ApiPublicResourcesReadRouteImport.update({
  id: '/api/public/resources/read',
  path: '/api/public/resources/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResourcesExchangeRoute =
  ApiPublicResourcesExchangeRouteImport.update({
    id: '/api/public/resources/exchange',
    path: '/api/public/resources/exchange',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirmed': typeof ConfirmedRoute
  '/intensive': typeof IntensiveRoute
  '/keynote': typeof KeynoteRoute
  '/mentorship': typeof MentorshipRoute
  '/next-keynote': typeof NextKeynoteRoute
  '/next-steps': typeof NextStepsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/strategy-intensive': typeof StrategyIntensiveRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/apply/mentorship': typeof ApplyMentorshipRoute
  '/calendar/day1.ics': typeof CalendarDay1DoticsRoute
  '/calendar/day2.ics': typeof CalendarDay2DoticsRoute
  '/offer/implementation-vault': typeof OfferImplementationVaultRoute
  '/offer/keynote': typeof OfferKeynoteRoute
  '/offer/mentorship': typeof OfferMentorshipRoute
  '/offer/strategy-intensive': typeof OfferStrategyIntensiveRoute
  '/offer/vip-upgrade': typeof OfferVipUpgradeRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/api/public/keynote-waitlist': typeof ApiPublicKeynoteWaitlistRoute
  '/api/public/mentorship-application': typeof ApiPublicMentorshipApplicationRoute
  '/api/public/resources/exchange': typeof ApiPublicResourcesExchangeRoute
  '/api/public/resources/read': typeof ApiPublicResourcesReadRoute
  '/api/public/webhooks/commas': typeof ApiPublicWebhooksCommasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirmed': typeof ConfirmedRoute
  '/intensive': typeof IntensiveRoute
  '/keynote': typeof KeynoteRoute
  '/mentorship': typeof MentorshipRoute
  '/next-keynote': typeof NextKeynoteRoute
  '/next-steps': typeof NextStepsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/strategy-intensive': typeof StrategyIntensiveRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/apply/mentorship': typeof ApplyMentorshipRoute
  '/calendar/day1.ics': typeof CalendarDay1DoticsRoute
  '/calendar/day2.ics': typeof CalendarDay2DoticsRoute
  '/offer/implementation-vault': typeof OfferImplementationVaultRoute
  '/offer/keynote': typeof OfferKeynoteRoute
  '/offer/mentorship': typeof OfferMentorshipRoute
  '/offer/strategy-intensive': typeof OfferStrategyIntensiveRoute
  '/offer/vip-upgrade': typeof OfferVipUpgradeRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/api/public/keynote-waitlist': typeof ApiPublicKeynoteWaitlistRoute
  '/api/public/mentorship-application': typeof ApiPublicMentorshipApplicationRoute
  '/api/public/resources/exchange': typeof ApiPublicResourcesExchangeRoute
  '/api/public/resources/read': typeof ApiPublicResourcesReadRoute
  '/api/public/webhooks/commas': typeof ApiPublicWebhooksCommasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirmed': typeof ConfirmedRoute
  '/intensive': typeof IntensiveRoute
  '/keynote': typeof KeynoteRoute
  '/mentorship': typeof MentorshipRoute
  '/next-keynote': typeof NextKeynoteRoute
  '/next-steps': typeof NextStepsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/strategy-intensive': typeof StrategyIntensiveRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/apply/mentorship': typeof ApplyMentorshipRoute
  '/calendar/day1.ics': typeof CalendarDay1DoticsRoute
  '/calendar/day2.ics': typeof CalendarDay2DoticsRoute
  '/offer/implementation-vault': typeof OfferImplementationVaultRoute
  '/offer/keynote': typeof OfferKeynoteRoute
  '/offer/mentorship': typeof OfferMentorshipRoute
  '/offer/strategy-intensive': typeof OfferStrategyIntensiveRoute
  '/offer/vip-upgrade': typeof OfferVipUpgradeRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/api/public/keynote-waitlist': typeof ApiPublicKeynoteWaitlistRoute
  '/api/public/mentorship-application': typeof ApiPublicMentorshipApplicationRoute
  '/api/public/resources/exchange': typeof ApiPublicResourcesExchangeRoute
  '/api/public/resources/read': typeof ApiPublicResourcesReadRoute
  '/api/public/webhooks/commas': typeof ApiPublicWebhooksCommasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/confirmed'
    | '/intensive'
    | '/keynote'
    | '/mentorship'
    | '/next-keynote'
    | '/next-steps'
    | '/privacy'
    | '/refund-policy'
    | '/resources'
    | '/strategy-intensive'
    | '/terms'
    | '/vault'
    | '/apply/mentorship'
    | '/calendar/day1.ics'
    | '/calendar/day2.ics'
    | '/offer/implementation-vault'
    | '/offer/keynote'
    | '/offer/mentorship'
    | '/offer/strategy-intensive'
    | '/offer/vip-upgrade'
    | '/resources/$slug'
    | '/api/public/keynote-waitlist'
    | '/api/public/mentorship-application'
    | '/api/public/resources/exchange'
    | '/api/public/resources/read'
    | '/api/public/webhooks/commas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/confirmed'
    | '/intensive'
    | '/keynote'
    | '/mentorship'
    | '/next-keynote'
    | '/next-steps'
    | '/privacy'
    | '/refund-policy'
    | '/resources'
    | '/strategy-intensive'
    | '/terms'
    | '/vault'
    | '/apply/mentorship'
    | '/calendar/day1.ics'
    | '/calendar/day2.ics'
    | '/offer/implementation-vault'
    | '/offer/keynote'
    | '/offer/mentorship'
    | '/offer/strategy-intensive'
    | '/offer/vip-upgrade'
    | '/resources/$slug'
    | '/api/public/keynote-waitlist'
    | '/api/public/mentorship-application'
    | '/api/public/resources/exchange'
    | '/api/public/resources/read'
    | '/api/public/webhooks/commas'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/confirmed'
    | '/intensive'
    | '/keynote'
    | '/mentorship'
    | '/next-keynote'
    | '/next-steps'
    | '/privacy'
    | '/refund-policy'
    | '/resources'
    | '/strategy-intensive'
    | '/terms'
    | '/vault'
    | '/apply/mentorship'
    | '/calendar/day1.ics'
    | '/calendar/day2.ics'
    | '/offer/implementation-vault'
    | '/offer/keynote'
    | '/offer/mentorship'
    | '/offer/strategy-intensive'
    | '/offer/vip-upgrade'
    | '/resources/$slug'
    | '/api/public/keynote-waitlist'
    | '/api/public/mentorship-application'
    | '/api/public/resources/exchange'
    | '/api/public/resources/read'
    | '/api/public/webhooks/commas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmedRoute: typeof ConfirmedRoute
  IntensiveRoute: typeof IntensiveRoute
  KeynoteRoute: typeof KeynoteRoute
  MentorshipRoute: typeof MentorshipRoute
  NextKeynoteRoute: typeof NextKeynoteRoute
  NextStepsRoute: typeof NextStepsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  StrategyIntensiveRoute: typeof StrategyIntensiveRoute
  TermsRoute: typeof TermsRoute
  VaultRoute: typeof VaultRoute
  ApplyMentorshipRoute: typeof ApplyMentorshipRoute
  CalendarDay1DoticsRoute: typeof CalendarDay1DoticsRoute
  CalendarDay2DoticsRoute: typeof CalendarDay2DoticsRoute
  OfferImplementationVaultRoute: typeof OfferImplementationVaultRoute
  OfferKeynoteRoute: typeof OfferKeynoteRoute
  OfferMentorshipRoute: typeof OfferMentorshipRoute
  OfferStrategyIntensiveRoute: typeof OfferStrategyIntensiveRoute
  OfferVipUpgradeRoute: typeof OfferVipUpgradeRoute
  ApiPublicKeynoteWaitlistRoute: typeof ApiPublicKeynoteWaitlistRoute
  ApiPublicMentorshipApplicationRoute: typeof ApiPublicMentorshipApplicationRoute
  ApiPublicResourcesExchangeRoute: typeof ApiPublicResourcesExchangeRoute
  ApiPublicResourcesReadRoute: typeof ApiPublicResourcesReadRoute
  ApiPublicWebhooksCommasRoute: typeof ApiPublicWebhooksCommasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy-intensive': {
      id: '/strategy-intensive'
      path: '/strategy-intensive'
      fullPath: '/strategy-intensive'
      preLoaderRoute: typeof StrategyIntensiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-steps': {
      id: '/next-steps'
      path: '/next-steps'
      fullPath: '/next-steps'
      preLoaderRoute: typeof NextStepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-keynote': {
      id: '/next-keynote'
      path: '/next-keynote'
      fullPath: '/next-keynote'
      preLoaderRoute: typeof NextKeynoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keynote': {
      id: '/keynote'
      path: '/keynote'
      fullPath: '/keynote'
      preLoaderRoute: typeof KeynoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intensive': {
      id: '/intensive'
      path: '/intensive'
      fullPath: '/intensive'
      preLoaderRoute: typeof IntensiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmed': {
      id: '/confirmed'
      path: '/confirmed'
      fullPath: '/confirmed'
      preLoaderRoute: typeof ConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/offer/vip-upgrade': {
      id: '/offer/vip-upgrade'
      path: '/offer/vip-upgrade'
      fullPath: '/offer/vip-upgrade'
      preLoaderRoute: typeof OfferVipUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/strategy-intensive': {
      id: '/offer/strategy-intensive'
      path: '/offer/strategy-intensive'
      fullPath: '/offer/strategy-intensive'
      preLoaderRoute: typeof OfferStrategyIntensiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/mentorship': {
      id: '/offer/mentorship'
      path: '/offer/mentorship'
      fullPath: '/offer/mentorship'
      preLoaderRoute: typeof OfferMentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/keynote': {
      id: '/offer/keynote'
      path: '/offer/keynote'
      fullPath: '/offer/keynote'
      preLoaderRoute: typeof OfferKeynoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/implementation-vault': {
      id: '/offer/implementation-vault'
      path: '/offer/implementation-vault'
      fullPath: '/offer/implementation-vault'
      preLoaderRoute: typeof OfferImplementationVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/day2.ics': {
      id: '/calendar/day2.ics'
      path: '/calendar/day2.ics'
      fullPath: '/calendar/day2.ics'
      preLoaderRoute: typeof CalendarDay2DoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/day1.ics': {
      id: '/calendar/day1.ics'
      path: '/calendar/day1.ics'
      fullPath: '/calendar/day1.ics'
      preLoaderRoute: typeof CalendarDay1DoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/mentorship': {
      id: '/apply/mentorship'
      path: '/apply/mentorship'
      fullPath: '/apply/mentorship'
      preLoaderRoute: typeof ApplyMentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mentorship-application': {
      id: '/api/public/mentorship-application'
      path: '/api/public/mentorship-application'
      fullPath: '/api/public/mentorship-application'
      preLoaderRoute: typeof ApiPublicMentorshipApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keynote-waitlist': {
      id: '/api/public/keynote-waitlist'
      path: '/api/public/keynote-waitlist'
      fullPath: '/api/public/keynote-waitlist'
      preLoaderRoute: typeof ApiPublicKeynoteWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/commas': {
      id: '/api/public/webhooks/commas'
      path: '/api/public/webhooks/commas'
      fullPath: '/api/public/webhooks/commas'
      preLoaderRoute: typeof ApiPublicWebhooksCommasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resources/read': {
      id: '/api/public/resources/read'
      path: '/api/public/resources/read'
      fullPath: '/api/public/resources/read'
      preLoaderRoute: typeof ApiPublicResourcesReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resources/exchange': {
      id: '/api/public/resources/exchange'
      path: '/api/public/resources/exchange'
      fullPath: '/api/public/resources/exchange'
      preLoaderRoute: typeof ApiPublicResourcesExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmedRoute: ConfirmedRoute,
  IntensiveRoute: IntensiveRoute,
  KeynoteRoute: KeynoteRoute,
  MentorshipRoute: MentorshipRoute,
  NextKeynoteRoute: NextKeynoteRoute,
  NextStepsRoute: NextStepsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  StrategyIntensiveRoute: StrategyIntensiveRoute,
  TermsRoute: TermsRoute,
  VaultRoute: VaultRoute,
  ApplyMentorshipRoute: ApplyMentorshipRoute,
  CalendarDay1DoticsRoute: CalendarDay1DoticsRoute,
  CalendarDay2DoticsRoute: CalendarDay2DoticsRoute,
  OfferImplementationVaultRoute: OfferImplementationVaultRoute,
  OfferKeynoteRoute: OfferKeynoteRoute,
  OfferMentorshipRoute: OfferMentorshipRoute,
  OfferStrategyIntensiveRoute: OfferStrategyIntensiveRoute,
  OfferVipUpgradeRoute: OfferVipUpgradeRoute,
  ApiPublicKeynoteWaitlistRoute: ApiPublicKeynoteWaitlistRoute,
  ApiPublicMentorshipApplicationRoute: ApiPublicMentorshipApplicationRoute,
  ApiPublicResourcesExchangeRoute: ApiPublicResourcesExchangeRoute,
  ApiPublicResourcesReadRoute: ApiPublicResourcesReadRoute,
  ApiPublicWebhooksCommasRoute: ApiPublicWebhooksCommasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
