/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VaultWelcomeRouteImport } from './routes/vault-welcome'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StrategyIntensiveRouteImport } from './routes/strategy-intensive'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NextStepsRouteImport } from './routes/next-steps'
import { Route as NextKeynoteRouteImport } from './routes/next-keynote'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as KeynoteRouteImport } from './routes/keynote'
import { Route as IntensiveRouteImport } from './routes/intensive'
import { Route as ConfirmedRouteImport } from './routes/confirmed'
import { Route as CommunicationPreferencesRouteImport } from './routes/communication-preferences'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReserveIndexRouteImport } from './routes/reserve/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ReserveVipRouteImport } from './routes/reserve/vip'
import { Route as ReserveVaultRouteImport } from './routes/reserve/vault'
import { Route as OfferVipUpgradeRouteImport } from './routes/offer/vip-upgrade'
import { Route as OfferStrategyIntensiveRouteImport } from './routes/offer/strategy-intensive'
import { Route as OfferMentorshipRouteImport } from './routes/offer/mentorship'
import { Route as OfferKeynoteRouteImport } from './routes/offer/keynote'
import { Route as OfferImplementationVaultRouteImport } from './routes/offer/implementation-vault'
import { Route as CalendarVaultWithSpinDoticsRouteImport } from './routes/calendar.vault-with-spin[.]ics'
import { Route as CalendarDay2DoticsRouteImport } from './routes/calendar.day2[.]ics'
import { Route as CalendarDay1DoticsRouteImport } from './routes/calendar.day1[.]ics'
import { Route as ApplyMentorshipRouteImport } from './routes/apply.mentorship'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ApiPublicSummitAuditRouteImport } from './routes/api/public/summit-audit'
import { Route as ApiPublicReserveUpgradeRouteImport } from './routes/api/public/reserve-upgrade'
import { Route as ApiPublicReserveRouteImport } from './routes/api/public/reserve'
import { Route as ApiPublicMentorshipApplicationRouteImport } from './routes/api/public/mentorship-application'
import { Route as ApiPublicKeynoteWaitlistRouteImport } from './routes/api/public/keynote-waitlist'
import { Route as ApiPublicCommunicationPreferencesRouteImport } from './routes/api/public/communication-preferences'
import { Route as ApiPublicWebhooksCommasRouteImport } from './routes/api/public/webhooks/commas'
import { Route as ApiPublicResourcesReadRouteImport } from './routes/api/public/resources/read'
import { Route as ApiPublicResourcesLogoutRouteImport } from './routes/api/public/resources/logout'
import { Route as ApiPublicResourcesExchangeRouteImport } from './routes/api/public/resources/exchange'
import { Route as ApiPublicResourcesEntitlementSummaryRouteImport } from './routes/api/public/resources/entitlement-summary'
import { Route as ApiPublicAdminSummitAuditRouteImport } from './routes/api/public/admin/summit-audit'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultWelcomeRoute = VaultWelcomeRouteImport.update({
  id: '/vault-welcome',
  path: '/vault-welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyIntensiveRoute = StrategyIntensiveRouteImport.update({
  id: '/strategy-intensive',
  path: '/strategy-intensive',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NextStepsRoute = NextStepsRouteImport.update({
  id: '/next-steps',
  path: '/next-steps',
  getParentRoute: () => rootRouteImport,
} as any)
const NextKeynoteRoute = NextKeynoteRouteImport.update({
  id: '/next-keynote',
  path: '/next-keynote',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const KeynoteRoute = KeynoteRouteImport.update({
  id: '/keynote',
  path: '/keynote',
  getParentRoute: () => rootRouteImport,
} as any)
const IntensiveRoute = IntensiveRouteImport.update({
  id: '/intensive',
  path: '/intensive',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmedRoute = ConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationPreferencesRoute =
  CommunicationPreferencesRouteImport.update({
    id: '/communication-preferences',
    path: '/communication-preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveIndexRoute = ReserveIndexRouteImport.update({
  id: '/reserve/',
  path: '/reserve/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const ReserveVipRoute = ReserveVipRouteImport.update({
  id: '/reserve/vip',
  path: '/reserve/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveVaultRoute = ReserveVaultRouteImport.update({
  id: '/reserve/vault',
  path: '/reserve/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferVipUpgradeRoute = OfferVipUpgradeRouteImport.update({
  id: '/offer/vip-upgrade',
  path: '/offer/vip-upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferStrategyIntensiveRoute = OfferStrategyIntensiveRouteImport.update({
  id: '/offer/strategy-intensive',
  path: '/offer/strategy-intensive',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferMentorshipRoute = OfferMentorshipRouteImport.update({
  id: '/offer/mentorship',
  path: '/offer/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferKeynoteRoute = OfferKeynoteRouteImport.update({
  id: '/offer/keynote',
  path: '/offer/keynote',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferImplementationVaultRoute =
  OfferImplementationVaultRouteImport.update({
    id: '/offer/implementation-vault',
    path: '/offer/implementation-vault',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalendarVaultWithSpinDoticsRoute =
  CalendarVaultWithSpinDoticsRouteImport.update({
    id: '/calendar/vault-with-spin.ics',
    path: '/calendar/vault-with-spin.ics',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalendarDay2DoticsRoute = CalendarDay2DoticsRouteImport.update({
  id: '/calendar/day2.ics',
  path: '/calendar/day2.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarDay1DoticsRoute = CalendarDay1DoticsRouteImport.update({
  id: '/calendar/day1.ics',
  path: '/calendar/day1.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyMentorshipRoute = ApplyMentorshipRouteImport.update({
  id: '/apply/mentorship',
  path: '/apply/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSummitAuditRoute = ApiPublicSummitAuditRouteImport.update({
  id: '/api/public/summit-audit',
  path: '/api/public/summit-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReserveUpgradeRoute = ApiPublicReserveUpgradeRouteImport.update({
  id: '/api/public/reserve-upgrade',
  path: '/api/public/reserve-upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReserveRoute = ApiPublicReserveRouteImport.update({
  id: '/api/public/reserve',
  path: '/api/public/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMentorshipApplicationRoute =
  ApiPublicMentorshipApplicationRouteImport.update({
    id: '/api/public/mentorship-application',
    path: '/api/public/mentorship-application',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKeynoteWaitlistRoute =
  ApiPublicKeynoteWaitlistRouteImport.update({
    id: '/api/public/keynote-waitlist',
    path: '/api/public/keynote-waitlist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCommunicationPreferencesRoute =
  ApiPublicCommunicationPreferencesRouteImport.update({
    id: '/api/public/communication-preferences',
    path: '/api/public/communication-preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksCommasRoute = ApiPublicWebhooksCommasRouteImport.update({
  id: '/api/public/webhooks/commas',
  path: '/api/public/webhooks/commas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResourcesReadRoute = ApiPublicResourcesReadRouteImport.update({
  id: '/api/public/resources/read',
  path: '/api/public/resources/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResourcesLogoutRoute =
  ApiPublicResourcesLogoutRouteImport.update({
    id: '/api/public/resources/logout',
    path: '/api/public/resources/logout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicResourcesExchangeRoute =
  ApiPublicResourcesExchangeRouteImport.update({
    id: '/api/public/resources/exchange',
    path: '/api/public/resources/exchange',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicResourcesEntitlementSummaryRoute =
  ApiPublicResourcesEntitlementSummaryRouteImport.update({
    id: '/api/public/resources/entitlement-summary',
    path: '/api/public/resources/entitlement-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSummitAuditRoute =
  ApiPublicAdminSummitAuditRouteImport.update({
    id: '/api/public/admin/summit-audit',
    path: '/api/public/admin/summit-audit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/checkout': typeof CheckoutRoute
  '/communication-preferences': typeof CommunicationPreferencesRoute
  '/confirmed': typeof ConfirmedRoute
  '/intensive': typeof IntensiveRoute
  '/keynote': typeof KeynoteRoute
  '/mentorship': typeof MentorshipRoute
  '/next-keynote': typeof NextKeynoteRoute
  '/next-steps': typeof NextStepsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/strategy-intensive': typeof StrategyIntensiveRoute
  '/terms': typeof TermsRoute
  '/vault-welcome': typeof VaultWelcomeRoute
  '/welcome': typeof WelcomeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/apply/mentorship': typeof ApplyMentorshipRoute
  '/calendar/day1.ics': typeof CalendarDay1DoticsRoute
  '/calendar/day2.ics': typeof CalendarDay2DoticsRoute
  '/calendar/vault-with-spin.ics': typeof CalendarVaultWithSpinDoticsRoute
  '/offer/implementation-vault': typeof OfferImplementationVaultRoute
  '/offer/keynote': typeof OfferKeynoteRoute
  '/offer/mentorship': typeof OfferMentorshipRoute
  '/offer/strategy-intensive': typeof OfferStrategyIntensiveRoute
  '/offer/vip-upgrade': typeof OfferVipUpgradeRoute
  '/reserve/vault': typeof ReserveVaultRoute
  '/reserve/vip': typeof ReserveVipRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/reserve/': typeof ReserveIndexRoute
  '/api/public/communication-preferences': typeof ApiPublicCommunicationPreferencesRoute
  '/api/public/keynote-waitlist': typeof ApiPublicKeynoteWaitlistRoute
  '/api/public/mentorship-application': typeof ApiPublicMentorshipApplicationRoute
  '/api/public/reserve': typeof ApiPublicReserveRoute
  '/api/public/reserve-upgrade': typeof ApiPublicReserveUpgradeRoute
  '/api/public/summit-audit': typeof ApiPublicSummitAuditRoute
  '/api/public/admin/summit-audit': typeof ApiPublicAdminSummitAuditRoute
  '/api/public/resources/entitlement-summary': typeof ApiPublicResourcesEntitlementSummaryRoute
  '/api/public/resources/exchange': typeof ApiPublicResourcesExchangeRoute
  '/api/public/resources/logout': typeof ApiPublicResourcesLogoutRoute
  '/api/public/resources/read': typeof ApiPublicResourcesReadRoute
  '/api/public/webhooks/commas': typeof ApiPublicWebhooksCommasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/checkout': typeof CheckoutRoute
  '/communication-preferences': typeof CommunicationPreferencesRoute
  '/confirmed': typeof ConfirmedRoute
  '/intensive': typeof IntensiveRoute
  '/keynote': typeof KeynoteRoute
  '/mentorship': typeof MentorshipRoute
  '/next-keynote': typeof NextKeynoteRoute
  '/next-steps': typeof NextStepsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/strategy-intensive': typeof StrategyIntensiveRoute
  '/terms': typeof TermsRoute
  '/vault-welcome': typeof VaultWelcomeRoute
  '/welcome': typeof WelcomeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/apply/mentorship': typeof ApplyMentorshipRoute
  '/calendar/day1.ics': typeof CalendarDay1DoticsRoute
  '/calendar/day2.ics': typeof CalendarDay2DoticsRoute
  '/calendar/vault-with-spin.ics': typeof CalendarVaultWithSpinDoticsRoute
  '/offer/implementation-vault': typeof OfferImplementationVaultRoute
  '/offer/keynote': typeof OfferKeynoteRoute
  '/offer/mentorship': typeof OfferMentorshipRoute
  '/offer/strategy-intensive': typeof OfferStrategyIntensiveRoute
  '/offer/vip-upgrade': typeof OfferVipUpgradeRoute
  '/reserve/vault': typeof ReserveVaultRoute
  '/reserve/vip': typeof ReserveVipRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/reserve': typeof ReserveIndexRoute
  '/api/public/communication-preferences': typeof ApiPublicCommunicationPreferencesRoute
  '/api/public/keynote-waitlist': typeof ApiPublicKeynoteWaitlistRoute
  '/api/public/mentorship-application': typeof ApiPublicMentorshipApplicationRoute
  '/api/public/reserve': typeof ApiPublicReserveRoute
  '/api/public/reserve-upgrade': typeof ApiPublicReserveUpgradeRoute
  '/api/public/summit-audit': typeof ApiPublicSummitAuditRoute
  '/api/public/admin/summit-audit': typeof ApiPublicAdminSummitAuditRoute
  '/api/public/resources/entitlement-summary': typeof ApiPublicResourcesEntitlementSummaryRoute
  '/api/public/resources/exchange': typeof ApiPublicResourcesExchangeRoute
  '/api/public/resources/logout': typeof ApiPublicResourcesLogoutRoute
  '/api/public/resources/read': typeof ApiPublicResourcesReadRoute
  '/api/public/webhooks/commas': typeof ApiPublicWebhooksCommasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/checkout': typeof CheckoutRoute
  '/communication-preferences': typeof CommunicationPreferencesRoute
  '/confirmed': typeof ConfirmedRoute
  '/intensive': typeof IntensiveRoute
  '/keynote': typeof KeynoteRoute
  '/mentorship': typeof MentorshipRoute
  '/next-keynote': typeof NextKeynoteRoute
  '/next-steps': typeof NextStepsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/strategy-intensive': typeof StrategyIntensiveRoute
  '/terms': typeof TermsRoute
  '/vault-welcome': typeof VaultWelcomeRoute
  '/welcome': typeof WelcomeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/apply/mentorship': typeof ApplyMentorshipRoute
  '/calendar/day1.ics': typeof CalendarDay1DoticsRoute
  '/calendar/day2.ics': typeof CalendarDay2DoticsRoute
  '/calendar/vault-with-spin.ics': typeof CalendarVaultWithSpinDoticsRoute
  '/offer/implementation-vault': typeof OfferImplementationVaultRoute
  '/offer/keynote': typeof OfferKeynoteRoute
  '/offer/mentorship': typeof OfferMentorshipRoute
  '/offer/strategy-intensive': typeof OfferStrategyIntensiveRoute
  '/offer/vip-upgrade': typeof OfferVipUpgradeRoute
  '/reserve/vault': typeof ReserveVaultRoute
  '/reserve/vip': typeof ReserveVipRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/reserve/': typeof ReserveIndexRoute
  '/api/public/communication-preferences': typeof ApiPublicCommunicationPreferencesRoute
  '/api/public/keynote-waitlist': typeof ApiPublicKeynoteWaitlistRoute
  '/api/public/mentorship-application': typeof ApiPublicMentorshipApplicationRoute
  '/api/public/reserve': typeof ApiPublicReserveRoute
  '/api/public/reserve-upgrade': typeof ApiPublicReserveUpgradeRoute
  '/api/public/summit-audit': typeof ApiPublicSummitAuditRoute
  '/api/public/admin/summit-audit': typeof ApiPublicAdminSummitAuditRoute
  '/api/public/resources/entitlement-summary': typeof ApiPublicResourcesEntitlementSummaryRoute
  '/api/public/resources/exchange': typeof ApiPublicResourcesExchangeRoute
  '/api/public/resources/logout': typeof ApiPublicResourcesLogoutRoute
  '/api/public/resources/read': typeof ApiPublicResourcesReadRoute
  '/api/public/webhooks/commas': typeof ApiPublicWebhooksCommasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/checkout'
    | '/communication-preferences'
    | '/confirmed'
    | '/intensive'
    | '/keynote'
    | '/mentorship'
    | '/next-keynote'
    | '/next-steps'
    | '/privacy'
    | '/refund-policy'
    | '/resources'
    | '/strategy-intensive'
    | '/terms'
    | '/vault-welcome'
    | '/welcome'
    | '/admin/audit'
    | '/apply/mentorship'
    | '/calendar/day1.ics'
    | '/calendar/day2.ics'
    | '/calendar/vault-with-spin.ics'
    | '/offer/implementation-vault'
    | '/offer/keynote'
    | '/offer/mentorship'
    | '/offer/strategy-intensive'
    | '/offer/vip-upgrade'
    | '/reserve/vault'
    | '/reserve/vip'
    | '/resources/$slug'
    | '/reserve/'
    | '/api/public/communication-preferences'
    | '/api/public/keynote-waitlist'
    | '/api/public/mentorship-application'
    | '/api/public/reserve'
    | '/api/public/reserve-upgrade'
    | '/api/public/summit-audit'
    | '/api/public/admin/summit-audit'
    | '/api/public/resources/entitlement-summary'
    | '/api/public/resources/exchange'
    | '/api/public/resources/logout'
    | '/api/public/resources/read'
    | '/api/public/webhooks/commas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/checkout'
    | '/communication-preferences'
    | '/confirmed'
    | '/intensive'
    | '/keynote'
    | '/mentorship'
    | '/next-keynote'
    | '/next-steps'
    | '/privacy'
    | '/refund-policy'
    | '/resources'
    | '/strategy-intensive'
    | '/terms'
    | '/vault-welcome'
    | '/welcome'
    | '/admin/audit'
    | '/apply/mentorship'
    | '/calendar/day1.ics'
    | '/calendar/day2.ics'
    | '/calendar/vault-with-spin.ics'
    | '/offer/implementation-vault'
    | '/offer/keynote'
    | '/offer/mentorship'
    | '/offer/strategy-intensive'
    | '/offer/vip-upgrade'
    | '/reserve/vault'
    | '/reserve/vip'
    | '/resources/$slug'
    | '/reserve'
    | '/api/public/communication-preferences'
    | '/api/public/keynote-waitlist'
    | '/api/public/mentorship-application'
    | '/api/public/reserve'
    | '/api/public/reserve-upgrade'
    | '/api/public/summit-audit'
    | '/api/public/admin/summit-audit'
    | '/api/public/resources/entitlement-summary'
    | '/api/public/resources/exchange'
    | '/api/public/resources/logout'
    | '/api/public/resources/read'
    | '/api/public/webhooks/commas'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/checkout'
    | '/communication-preferences'
    | '/confirmed'
    | '/intensive'
    | '/keynote'
    | '/mentorship'
    | '/next-keynote'
    | '/next-steps'
    | '/privacy'
    | '/refund-policy'
    | '/resources'
    | '/strategy-intensive'
    | '/terms'
    | '/vault-welcome'
    | '/welcome'
    | '/admin/audit'
    | '/apply/mentorship'
    | '/calendar/day1.ics'
    | '/calendar/day2.ics'
    | '/calendar/vault-with-spin.ics'
    | '/offer/implementation-vault'
    | '/offer/keynote'
    | '/offer/mentorship'
    | '/offer/strategy-intensive'
    | '/offer/vip-upgrade'
    | '/reserve/vault'
    | '/reserve/vip'
    | '/resources/$slug'
    | '/reserve/'
    | '/api/public/communication-preferences'
    | '/api/public/keynote-waitlist'
    | '/api/public/mentorship-application'
    | '/api/public/reserve'
    | '/api/public/reserve-upgrade'
    | '/api/public/summit-audit'
    | '/api/public/admin/summit-audit'
    | '/api/public/resources/entitlement-summary'
    | '/api/public/resources/exchange'
    | '/api/public/resources/logout'
    | '/api/public/resources/read'
    | '/api/public/webhooks/commas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CheckoutRoute: typeof CheckoutRoute
  CommunicationPreferencesRoute: typeof CommunicationPreferencesRoute
  ConfirmedRoute: typeof ConfirmedRoute
  IntensiveRoute: typeof IntensiveRoute
  KeynoteRoute: typeof KeynoteRoute
  MentorshipRoute: typeof MentorshipRoute
  NextKeynoteRoute: typeof NextKeynoteRoute
  NextStepsRoute: typeof NextStepsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  StrategyIntensiveRoute: typeof StrategyIntensiveRoute
  TermsRoute: typeof TermsRoute
  VaultWelcomeRoute: typeof VaultWelcomeRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminAuditRoute: typeof AdminAuditRoute
  ApplyMentorshipRoute: typeof ApplyMentorshipRoute
  CalendarDay1DoticsRoute: typeof CalendarDay1DoticsRoute
  CalendarDay2DoticsRoute: typeof CalendarDay2DoticsRoute
  CalendarVaultWithSpinDoticsRoute: typeof CalendarVaultWithSpinDoticsRoute
  OfferImplementationVaultRoute: typeof OfferImplementationVaultRoute
  OfferKeynoteRoute: typeof OfferKeynoteRoute
  OfferMentorshipRoute: typeof OfferMentorshipRoute
  OfferStrategyIntensiveRoute: typeof OfferStrategyIntensiveRoute
  OfferVipUpgradeRoute: typeof OfferVipUpgradeRoute
  ReserveVaultRoute: typeof ReserveVaultRoute
  ReserveVipRoute: typeof ReserveVipRoute
  ReserveIndexRoute: typeof ReserveIndexRoute
  ApiPublicCommunicationPreferencesRoute: typeof ApiPublicCommunicationPreferencesRoute
  ApiPublicKeynoteWaitlistRoute: typeof ApiPublicKeynoteWaitlistRoute
  ApiPublicMentorshipApplicationRoute: typeof ApiPublicMentorshipApplicationRoute
  ApiPublicReserveRoute: typeof ApiPublicReserveRoute
  ApiPublicReserveUpgradeRoute: typeof ApiPublicReserveUpgradeRoute
  ApiPublicSummitAuditRoute: typeof ApiPublicSummitAuditRoute
  ApiPublicAdminSummitAuditRoute: typeof ApiPublicAdminSummitAuditRoute
  ApiPublicResourcesEntitlementSummaryRoute: typeof ApiPublicResourcesEntitlementSummaryRoute
  ApiPublicResourcesExchangeRoute: typeof ApiPublicResourcesExchangeRoute
  ApiPublicResourcesLogoutRoute: typeof ApiPublicResourcesLogoutRoute
  ApiPublicResourcesReadRoute: typeof ApiPublicResourcesReadRoute
  ApiPublicWebhooksCommasRoute: typeof ApiPublicWebhooksCommasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault-welcome': {
      id: '/vault-welcome'
      path: '/vault-welcome'
      fullPath: '/vault-welcome'
      preLoaderRoute: typeof VaultWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy-intensive': {
      id: '/strategy-intensive'
      path: '/strategy-intensive'
      fullPath: '/strategy-intensive'
      preLoaderRoute: typeof StrategyIntensiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-steps': {
      id: '/next-steps'
      path: '/next-steps'
      fullPath: '/next-steps'
      preLoaderRoute: typeof NextStepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-keynote': {
      id: '/next-keynote'
      path: '/next-keynote'
      fullPath: '/next-keynote'
      preLoaderRoute: typeof NextKeynoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keynote': {
      id: '/keynote'
      path: '/keynote'
      fullPath: '/keynote'
      preLoaderRoute: typeof KeynoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intensive': {
      id: '/intensive'
      path: '/intensive'
      fullPath: '/intensive'
      preLoaderRoute: typeof IntensiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmed': {
      id: '/confirmed'
      path: '/confirmed'
      fullPath: '/confirmed'
      preLoaderRoute: typeof ConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication-preferences': {
      id: '/communication-preferences'
      path: '/communication-preferences'
      fullPath: '/communication-preferences'
      preLoaderRoute: typeof CommunicationPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve/': {
      id: '/reserve/'
      path: '/reserve'
      fullPath: '/reserve/'
      preLoaderRoute: typeof ReserveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/reserve/vip': {
      id: '/reserve/vip'
      path: '/reserve/vip'
      fullPath: '/reserve/vip'
      preLoaderRoute: typeof ReserveVipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve/vault': {
      id: '/reserve/vault'
      path: '/reserve/vault'
      fullPath: '/reserve/vault'
      preLoaderRoute: typeof ReserveVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/vip-upgrade': {
      id: '/offer/vip-upgrade'
      path: '/offer/vip-upgrade'
      fullPath: '/offer/vip-upgrade'
      preLoaderRoute: typeof OfferVipUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/strategy-intensive': {
      id: '/offer/strategy-intensive'
      path: '/offer/strategy-intensive'
      fullPath: '/offer/strategy-intensive'
      preLoaderRoute: typeof OfferStrategyIntensiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/mentorship': {
      id: '/offer/mentorship'
      path: '/offer/mentorship'
      fullPath: '/offer/mentorship'
      preLoaderRoute: typeof OfferMentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/keynote': {
      id: '/offer/keynote'
      path: '/offer/keynote'
      fullPath: '/offer/keynote'
      preLoaderRoute: typeof OfferKeynoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/implementation-vault': {
      id: '/offer/implementation-vault'
      path: '/offer/implementation-vault'
      fullPath: '/offer/implementation-vault'
      preLoaderRoute: typeof OfferImplementationVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/vault-with-spin.ics': {
      id: '/calendar/vault-with-spin.ics'
      path: '/calendar/vault-with-spin.ics'
      fullPath: '/calendar/vault-with-spin.ics'
      preLoaderRoute: typeof CalendarVaultWithSpinDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/day2.ics': {
      id: '/calendar/day2.ics'
      path: '/calendar/day2.ics'
      fullPath: '/calendar/day2.ics'
      preLoaderRoute: typeof CalendarDay2DoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/day1.ics': {
      id: '/calendar/day1.ics'
      path: '/calendar/day1.ics'
      fullPath: '/calendar/day1.ics'
      preLoaderRoute: typeof CalendarDay1DoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/mentorship': {
      id: '/apply/mentorship'
      path: '/apply/mentorship'
      fullPath: '/apply/mentorship'
      preLoaderRoute: typeof ApplyMentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/summit-audit': {
      id: '/api/public/summit-audit'
      path: '/api/public/summit-audit'
      fullPath: '/api/public/summit-audit'
      preLoaderRoute: typeof ApiPublicSummitAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reserve-upgrade': {
      id: '/api/public/reserve-upgrade'
      path: '/api/public/reserve-upgrade'
      fullPath: '/api/public/reserve-upgrade'
      preLoaderRoute: typeof ApiPublicReserveUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reserve': {
      id: '/api/public/reserve'
      path: '/api/public/reserve'
      fullPath: '/api/public/reserve'
      preLoaderRoute: typeof ApiPublicReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mentorship-application': {
      id: '/api/public/mentorship-application'
      path: '/api/public/mentorship-application'
      fullPath: '/api/public/mentorship-application'
      preLoaderRoute: typeof ApiPublicMentorshipApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keynote-waitlist': {
      id: '/api/public/keynote-waitlist'
      path: '/api/public/keynote-waitlist'
      fullPath: '/api/public/keynote-waitlist'
      preLoaderRoute: typeof ApiPublicKeynoteWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/communication-preferences': {
      id: '/api/public/communication-preferences'
      path: '/api/public/communication-preferences'
      fullPath: '/api/public/communication-preferences'
      preLoaderRoute: typeof ApiPublicCommunicationPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/commas': {
      id: '/api/public/webhooks/commas'
      path: '/api/public/webhooks/commas'
      fullPath: '/api/public/webhooks/commas'
      preLoaderRoute: typeof ApiPublicWebhooksCommasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resources/read': {
      id: '/api/public/resources/read'
      path: '/api/public/resources/read'
      fullPath: '/api/public/resources/read'
      preLoaderRoute: typeof ApiPublicResourcesReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resources/logout': {
      id: '/api/public/resources/logout'
      path: '/api/public/resources/logout'
      fullPath: '/api/public/resources/logout'
      preLoaderRoute: typeof ApiPublicResourcesLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resources/exchange': {
      id: '/api/public/resources/exchange'
      path: '/api/public/resources/exchange'
      fullPath: '/api/public/resources/exchange'
      preLoaderRoute: typeof ApiPublicResourcesExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resources/entitlement-summary': {
      id: '/api/public/resources/entitlement-summary'
      path: '/api/public/resources/entitlement-summary'
      fullPath: '/api/public/resources/entitlement-summary'
      preLoaderRoute: typeof ApiPublicResourcesEntitlementSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/summit-audit': {
      id: '/api/public/admin/summit-audit'
      path: '/api/public/admin/summit-audit'
      fullPath: '/api/public/admin/summit-audit'
      preLoaderRoute: typeof ApiPublicAdminSummitAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CheckoutRoute: CheckoutRoute,
  CommunicationPreferencesRoute: CommunicationPreferencesRoute,
  ConfirmedRoute: ConfirmedRoute,
  IntensiveRoute: IntensiveRoute,
  KeynoteRoute: KeynoteRoute,
  MentorshipRoute: MentorshipRoute,
  NextKeynoteRoute: NextKeynoteRoute,
  NextStepsRoute: NextStepsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  StrategyIntensiveRoute: StrategyIntensiveRoute,
  TermsRoute: TermsRoute,
  VaultWelcomeRoute: VaultWelcomeRoute,
  WelcomeRoute: WelcomeRoute,
  AdminAuditRoute: AdminAuditRoute,
  ApplyMentorshipRoute: ApplyMentorshipRoute,
  CalendarDay1DoticsRoute: CalendarDay1DoticsRoute,
  CalendarDay2DoticsRoute: CalendarDay2DoticsRoute,
  CalendarVaultWithSpinDoticsRoute: CalendarVaultWithSpinDoticsRoute,
  OfferImplementationVaultRoute: OfferImplementationVaultRoute,
  OfferKeynoteRoute: OfferKeynoteRoute,
  OfferMentorshipRoute: OfferMentorshipRoute,
  OfferStrategyIntensiveRoute: OfferStrategyIntensiveRoute,
  OfferVipUpgradeRoute: OfferVipUpgradeRoute,
  ReserveVaultRoute: ReserveVaultRoute,
  ReserveVipRoute: ReserveVipRoute,
  ReserveIndexRoute: ReserveIndexRoute,
  ApiPublicCommunicationPreferencesRoute:
    ApiPublicCommunicationPreferencesRoute,
  ApiPublicKeynoteWaitlistRoute: ApiPublicKeynoteWaitlistRoute,
  ApiPublicMentorshipApplicationRoute: ApiPublicMentorshipApplicationRoute,
  ApiPublicReserveRoute: ApiPublicReserveRoute,
  ApiPublicReserveUpgradeRoute: ApiPublicReserveUpgradeRoute,
  ApiPublicSummitAuditRoute: ApiPublicSummitAuditRoute,
  ApiPublicAdminSummitAuditRoute: ApiPublicAdminSummitAuditRoute,
  ApiPublicResourcesEntitlementSummaryRoute:
    ApiPublicResourcesEntitlementSummaryRoute,
  ApiPublicResourcesExchangeRoute: ApiPublicResourcesExchangeRoute,
  ApiPublicResourcesLogoutRoute: ApiPublicResourcesLogoutRoute,
  ApiPublicResourcesReadRoute: ApiPublicResourcesReadRoute,
  ApiPublicWebhooksCommasRoute: ApiPublicWebhooksCommasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
